[package]
name = "system-monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
sysinfo = "0.37"
chrono = { version = "0.4", features = ["clock"] }
dirs = "5.0"
ratatui = "0.29"
crossterm = "0.28"
